id = "cursor-theme"
name = "Cursor Theme"
version = "0.0.1"
schema_version = 1
authors = ["Jenil Desai <jenildev91@gmail.com>"]
description = "Cursor One Dark theme for Zed"
repository = "https://github.com/Jenil-Desai/cursor-theme"
