id = "cursor"
name = "Cursor"
version = "0.0.1"
schema_version = 1
authors = ["Jenil Desai <jenildev91@gmail.com>"]
description = "Cursor Dark Theme"
repository = "https://github.com/Jenil-Desai/Zed-Cursor-Theme"
